name: CI/CD for Terraform and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_FILE_DIR: "case1-FastAPI-CloudRun"
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: "case1-fastapi-cloudrun"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build  Docker image
        run: |
          IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}-${{ github.ref_name }}:${{ github.sha }}
          docker build -t ${{ env.IMAGE }} -f ${{ env.DOCKER_FILE_DIR }}/Dockerfile ${{ env.DOCKER_FILE_DIR }}/

      - name: Push Docker image
        run: |
          IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}-${{ github.ref_name }}:${{ github.sha }}
          docker push ${{ env.IMAGE }}

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1

      # - name: Initialize Terraform
      #   run: terraform init
      #   working-directory:

      # - name: Apply Terraform
      #   run: terraform apply -auto-approve -var="image=${env.IMAGE}"
      #   working-directory: terraform/environments/${{ github.ref_name }}
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
